@echo off
cd /d "c:\Users\91735\Desktop\projects\yt-chat-application\frontend"
echo Installing react-scripts...
npm install react-scripts@5.0.1 --save-exact --legacy-peer-deps --no-audit --no-fund
echo Installing all dependencies...
npm install --legacy-peer-deps --no-audit --no-fund
echo Starting frontend...
npm start
